name: iOS KaloriX Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Kodları Al
        uses: actions/checkout@v4
      - name: Node.js Kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Gerekli Paketleri Yükle
        run: npm install
      - name: iOS Projesini Oluştur
        run: npx cap add ios
      - name: Uygulamayı Derle (İmzasız)
        run: |
          cd ios/App
          xcodebuild clean build -workspace App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO SYMROOT=$(PWD)/build
      - name: IPA Dosyasını Paketle
        run: |
          mkdir -p Payload
          mv ios/App/build/Release-iphoneos/App.app Payload/
          zip -r KaloriX.ipa Payload
      - name: Kurulum Dosyasını İndirmeye Hazırla
        uses: actions/upload-artifact@v4
        with:
          name: KaloriX-Uygulamasi
          path: KaloriX.ipa
